# Learn more → https://github.com/TryGhost/action-deploy-theme#getting-started
name: Deploy Theme
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    #  checks for runners with label runner-k3s, if active use it, failover to ubuntu:latest
    runs-on: 
      labels: ${{ matrix.labels }} 
    strategy:
      matrix:
        labels: [runner-k3s, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: Deploy Ghost Theme to ElClaustro.cl
        continue-on-error: true
        uses: TryGhost/action-deploy-theme@v1.6.3
        with:
          api-url: ${{ secrets.ELCLAUSTRO_API_URL }}
          api-key: ${{ secrets.ELCLAUSTRO_ADMIN_API_KEY }}
      
      - name: Deploy Ghost Theme to SREDevOps.cl
        uses: TryGhost/action-deploy-theme@v1.6.3
        continue-on-error: false
        with:
          api-url: ${{ secrets.SREDEVOPS_API_URL }}
          api-key: ${{ secrets.SREDEVOPS_ADMIN_API_KEY }}
